# Generated by Django 5.1 on 2024-09-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publication',
            new_name='publication_year',
        ),
    ]
